name: prosody-tor

services:
  prosody:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tor_data:/var/lib/tor
      - ./prosody_tor_service:/var/lib/tor/prosody
      - ./prosody_data:/var/lib/prosody
      - ./prosody_certs:/etc/prosody/certs/host
    restart: unless-stopped